
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE SCHEMA IF NOT EXISTS "supabase_migrations";

ALTER SCHEMA "supabase_migrations" OWNER TO "postgres";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."external_datasource_name" AS ENUM (
    'twitch_igdb',
    'nointro',
    'thegamesdb'
);

ALTER TYPE "public"."external_datasource_name" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."game_external_links" (
    "id" bigint NOT NULL,
    "game_id" bigint NOT NULL,
    "external_id" bigint NOT NULL,
    "external_source_name" public.external_datasource_name NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."game_external_links" OWNER TO "postgres";

ALTER TABLE "public"."game_external_links" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_external_links_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."game_release_external_links" (
    "id" bigint NOT NULL,
    "game_release_id" bigint NOT NULL,
    "external_id" bigint NOT NULL,
    "external_source_name" public.external_datasource_name NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."game_release_external_links" OWNER TO "postgres";

ALTER TABLE "public"."game_release_external_links" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_release_external_links_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."game_releases" (
    "id" bigint NOT NULL,
    "game_id" bigint NOT NULL,
    "platform_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "region_id" bigint,
    "release_date" timestamp with time zone
);

ALTER TABLE "public"."game_releases" OWNER TO "postgres";

ALTER TABLE "public"."game_releases" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_releases_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."games" (
    "id" bigint NOT NULL,
    "name" text NOT NULL,
    "slug" text NOT NULL,
    "sort_key" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."games" OWNER TO "postgres";

ALTER TABLE "public"."games" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."games_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."platforms" (
    "id" bigint NOT NULL,
    "name" text NOT NULL,
    "short_name" text NOT NULL,
    "slug" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."platforms" OWNER TO "postgres";

ALTER TABLE "public"."platforms" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."platforms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."regions" (
    "id" bigint NOT NULL,
    "name" text NOT NULL,
    "slug" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."regions" OWNER TO "postgres";

ALTER TABLE "public"."regions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."regions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."rom_external_links" (
    "id" bigint NOT NULL,
    "rom_id" bigint NOT NULL,
    "external_id" bigint NOT NULL,
    "external_source_name" public.external_datasource_name NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."rom_external_links" OWNER TO "postgres";

ALTER TABLE "public"."rom_external_links" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rom_external_links_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."roms" (
    "id" bigint NOT NULL,
    "game_release_id" bigint NOT NULL,
    "filename" text,
    "filesize_bytes" bigint,
    "md5" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."roms" OWNER TO "postgres";

ALTER TABLE "public"."roms" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "supabase_migrations"."schema_migrations" (
    "version" text NOT NULL,
    "statements" text[],
    "name" text
);

ALTER TABLE "supabase_migrations"."schema_migrations" OWNER TO "postgres";

ALTER TABLE ONLY "public"."game_external_links"
    ADD CONSTRAINT "game_external_links_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."game_release_external_links"
    ADD CONSTRAINT "game_release_external_links_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."game_releases"
    ADD CONSTRAINT "game_releases_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."platforms"
    ADD CONSTRAINT "platforms_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."platforms"
    ADD CONSTRAINT "platforms_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."platforms"
    ADD CONSTRAINT "platforms_short_name_key" UNIQUE ("short_name");

ALTER TABLE ONLY "public"."platforms"
    ADD CONSTRAINT "platforms_slug_key" UNIQUE ("slug");

ALTER TABLE ONLY "public"."regions"
    ADD CONSTRAINT "regions_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."regions"
    ADD CONSTRAINT "regions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."regions"
    ADD CONSTRAINT "regions_slug_key" UNIQUE ("slug");

ALTER TABLE ONLY "public"."rom_external_links"
    ADD CONSTRAINT "rom_external_links_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."roms"
    ADD CONSTRAINT "roms_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "supabase_migrations"."schema_migrations"
    ADD CONSTRAINT "schema_migrations_pkey" PRIMARY KEY ("version");

ALTER TABLE ONLY "public"."game_external_links"
    ADD CONSTRAINT "game_external_links_game_id_fkey" FOREIGN KEY (game_id) REFERENCES public.games(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."game_release_external_links"
    ADD CONSTRAINT "game_release_external_links_game_release_id_fkey" FOREIGN KEY (game_release_id) REFERENCES public.game_releases(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."game_releases"
    ADD CONSTRAINT "game_releases_game_id_fkey" FOREIGN KEY (game_id) REFERENCES public.games(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."game_releases"
    ADD CONSTRAINT "game_releases_platform_id_fkey" FOREIGN KEY (platform_id) REFERENCES public.platforms(id) ON UPDATE CASCADE;

ALTER TABLE ONLY "public"."game_releases"
    ADD CONSTRAINT "game_releases_region_id_fkey" FOREIGN KEY (region_id) REFERENCES public.regions(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."rom_external_links"
    ADD CONSTRAINT "rom_external_links_rom_id_fkey" FOREIGN KEY (rom_id) REFERENCES public.roms(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."roms"
    ADD CONSTRAINT "roms_game_release_id_fkey" FOREIGN KEY (game_release_id) REFERENCES public.game_releases(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE POLICY "Enable read access for all users" ON "public"."platforms" FOR SELECT USING (true);

ALTER TABLE "public"."game_external_links" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."game_release_external_links" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."game_releases" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."games" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."platforms" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."regions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."rom_external_links" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."roms" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."game_external_links" TO "anon";
GRANT ALL ON TABLE "public"."game_external_links" TO "authenticated";
GRANT ALL ON TABLE "public"."game_external_links" TO "service_role";

GRANT ALL ON SEQUENCE "public"."game_external_links_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."game_external_links_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."game_external_links_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."game_release_external_links" TO "anon";
GRANT ALL ON TABLE "public"."game_release_external_links" TO "authenticated";
GRANT ALL ON TABLE "public"."game_release_external_links" TO "service_role";

GRANT ALL ON SEQUENCE "public"."game_release_external_links_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."game_release_external_links_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."game_release_external_links_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."game_releases" TO "anon";
GRANT ALL ON TABLE "public"."game_releases" TO "authenticated";
GRANT ALL ON TABLE "public"."game_releases" TO "service_role";

GRANT ALL ON SEQUENCE "public"."game_releases_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."game_releases_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."game_releases_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."games" TO "anon";
GRANT ALL ON TABLE "public"."games" TO "authenticated";
GRANT ALL ON TABLE "public"."games" TO "service_role";

GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."games_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."platforms" TO "anon";
GRANT ALL ON TABLE "public"."platforms" TO "authenticated";
GRANT ALL ON TABLE "public"."platforms" TO "service_role";

GRANT ALL ON SEQUENCE "public"."platforms_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."platforms_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."platforms_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."regions" TO "anon";
GRANT ALL ON TABLE "public"."regions" TO "authenticated";
GRANT ALL ON TABLE "public"."regions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."regions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."regions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."regions_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."rom_external_links" TO "anon";
GRANT ALL ON TABLE "public"."rom_external_links" TO "authenticated";
GRANT ALL ON TABLE "public"."rom_external_links" TO "service_role";

GRANT ALL ON SEQUENCE "public"."rom_external_links_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rom_external_links_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rom_external_links_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."roms" TO "anon";
GRANT ALL ON TABLE "public"."roms" TO "authenticated";
GRANT ALL ON TABLE "public"."roms" TO "service_role";

GRANT ALL ON SEQUENCE "public"."roms_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roms_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roms_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
